export const places = [
    'Abijo',
    'Abule Egba',
    'Abule-Egba',
    'Abule-Oja',
    'Agege',
    'Agidingbi',
    'Aguda',
    'Agungi',
    'Ajah',
    'Ajao Estate',
    'Ajegunle',
    'Akerele',
    'Akoka',
    'Akowonjo',
    'Alagbado',
    'Alakuko',
    'Alapere',
    'Alausa',
    'Alimosho',
    'Amuwo-Odofin',
    'Anthony Village',
    'Apapa',
    'Awolowo Road',
    'Badagry',
    'Bariga',
    'Bourdillon',
    'Coker',
    'Dolphin Estate',
    'Dopemu',
    'Dopemu-Agege',
    'Ebutte Metta',
    'Egbeda',
    'Egbeda-Idimu',
    'Egba',
    'Ejigbo',
    'Ekoro',
    'Epe',
    'Fadeyi',
    'Festac Town',
    'Gbagada',
    'Gboko',
    'Iba',
    'Ibeju-Lekki',
    'Idimu',
    'Igando',
    'Igbo Efon',
    'Igbobi College',
    'Igbogbo',
    'Ikeja',
    'Ikeja Gra',
    'Ikorodu',
    'Ikosi Ketu',
    'Ikota',
    'Ikotun',
    'Ikoyi',
    'Ilasamaja',
    'Ilashe',
    'Ilupeju',
    'Ipaja',
    'Ipakodo',
    'Iponri',
    'Irawo',
    'Isolo',
    'Jibowu',
    'Ketu',
    'Kosofe',
    'Kuramo Beach',
    'Lagos Island',
    'Lagos Mainland',
    'Lakowe',
    'Lekki',
    'Lekki Phase 1',
    'Lekki Phase 2',
    'Lekki Peninsula',
    'Magodo',
    'Makoko',
    'Marina',
    'Maryland',
    'Mende',
    'Mile 12',
    'Mushin',
    'Obalende',
    'Obanikoro',
    'Ogba',
    'Ogudu',
    'Ojodu',
    'Ojota',
    'Ojuelegba',
    'Ojota',
    'Okokomaiko',
    'Okota',
    'Ologolo',
    'Onike',
    'Oniru',
    'Oniru Estate',
    'Opebi',
    'Oregun',
    'Orile',
    'Oshodi',
    'Oworonshoki',
    'Palmgrove',
    'Palmgrove Estate',
    'Sabo',
    'Satellite Town',
    'Shomolu',
    'Sogunle',
    'Songotedo',
    'Surulere',
    'Takwa Bay',
    'Tejuosho',
    'Victoria Garden City',
    'Victoria Island',
    'Yaba',
    'Yaba College Of Technology',
    'Others Places...',
];